### ISSUE TITLE
Добавить возможность публикации пакетов в aptly

### ISSUE THREAD

**Issue by pumbaEO** [vorohorio/1c-enterprise83-client-repack#2]
При использовании aptly как сервер для раздачи пакетов, хотелось бы иметь возможность перепакованные пакеты сразу же добавлять в индекс aptly с передачей параметра типа репозитария testing, stable и т.д.

**Comment by vorohorio** [comment]
У меня локально так и делается.
в конце скрипта добавлены 2 строчки:

```
aptly repo add -force-replace=true ubuntu 1c-enterprise83-client-repack-${Version}_${Architecture}.deb
aptly publish update -force-overwrite=true -passphrase="${GPG_PASSWORD}" precise local
```

При публикации я это убрал намеренно.
Мне кажется проще сделать так:
- создать скрипт-обертку
- из него вызвать скрипт перепаковки
- из него обновить свой репозиторий

Как считаете?

**Comment by pumbaEO** [comment]
Согласен, правильней отдельно выделить в создать скрипт-обертку и там уже добавлять, тогда и модульность поддерживаем и локально отладка перепаковки будет проще.
